#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 139
#define LARGE_STATE_COUNT 6
#define SYMBOL_COUNT 55
#define ALIAS_COUNT 0
#define TOKEN_COUNT 30
#define EXTERNAL_TOKEN_COUNT 9
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define PRODUCTION_ID_COUNT 1

enum {
  anon_sym_LT_BANG = 1,
  aux_sym_doctype_token1 = 2,
  anon_sym_GT = 3,
  sym__doctype = 4,
  anon_sym_LT = 5,
  anon_sym_LT_AT = 6,
  anon_sym_LT_POUND = 7,
  anon_sym_if = 8,
  sym_identifier = 9,
  anon_sym_SLASH_GT = 10,
  anon_sym_LT_SLASH = 11,
  anon_sym_LT_SLASH_AT = 12,
  anon_sym_LT_SLASH_POUND = 13,
  anon_sym_EQ = 14,
  sym_attribute_name = 15,
  sym_attribute_value = 16,
  anon_sym_SQUOTE = 17,
  aux_sym_quoted_attribute_value_token1 = 18,
  anon_sym_DQUOTE = 19,
  aux_sym_quoted_attribute_value_token2 = 20,
  sym_text = 21,
  sym__start_tag_name = 22,
  sym__script_start_tag_name = 23,
  sym__style_start_tag_name = 24,
  sym__end_tag_name = 25,
  sym_erroneous_end_tag_name = 26,
  sym__implicit_end_tag = 27,
  sym_raw_text = 28,
  sym_comment = 29,
  sym_fragment = 30,
  sym_doctype = 31,
  sym__node = 32,
  sym_element = 33,
  sym_fm_macro = 34,
  sym_fm_directive = 35,
  sym_script_element = 36,
  sym_style_element = 37,
  sym_start_tag = 38,
  sym_fm_macro_start_tag = 39,
  sym_fm_directive_start_tag = 40,
  sym_fm_if_directive_start_tag = 41,
  sym__expression = 42,
  sym_script_start_tag = 43,
  sym_style_start_tag = 44,
  sym_self_closing_tag = 45,
  sym_fm_macro_self_closing_tag = 46,
  sym_end_tag = 47,
  sym_fm_macro_end_tag = 48,
  sym_fm_directive_end_tag = 49,
  sym_erroneous_end_tag = 50,
  sym_attribute = 51,
  sym_quoted_attribute_value = 52,
  aux_sym_fragment_repeat1 = 53,
  aux_sym_start_tag_repeat1 = 54,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LT_BANG] = "<!",
  [aux_sym_doctype_token1] = "doctype_token1",
  [anon_sym_GT] = ">",
  [sym__doctype] = "doctype",
  [anon_sym_LT] = "<",
  [anon_sym_LT_AT] = "<@",
  [anon_sym_LT_POUND] = "<#",
  [anon_sym_if] = "if",
  [sym_identifier] = "identifier",
  [anon_sym_SLASH_GT] = "/>",
  [anon_sym_LT_SLASH] = "</",
  [anon_sym_LT_SLASH_AT] = "</@",
  [anon_sym_LT_SLASH_POUND] = "</#",
  [anon_sym_EQ] = "=",
  [sym_attribute_name] = "attribute_name",
  [sym_attribute_value] = "attribute_value",
  [anon_sym_SQUOTE] = "'",
  [aux_sym_quoted_attribute_value_token1] = "attribute_value",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_quoted_attribute_value_token2] = "attribute_value",
  [sym_text] = "text",
  [sym__start_tag_name] = "tag_name",
  [sym__script_start_tag_name] = "tag_name",
  [sym__style_start_tag_name] = "tag_name",
  [sym__end_tag_name] = "tag_name",
  [sym_erroneous_end_tag_name] = "erroneous_end_tag_name",
  [sym__implicit_end_tag] = "_implicit_end_tag",
  [sym_raw_text] = "raw_text",
  [sym_comment] = "comment",
  [sym_fragment] = "fragment",
  [sym_doctype] = "doctype",
  [sym__node] = "_node",
  [sym_element] = "element",
  [sym_fm_macro] = "fm_macro",
  [sym_fm_directive] = "fm_directive",
  [sym_script_element] = "script_element",
  [sym_style_element] = "style_element",
  [sym_start_tag] = "start_tag",
  [sym_fm_macro_start_tag] = "fm_macro_start_tag",
  [sym_fm_directive_start_tag] = "fm_directive_start_tag",
  [sym_fm_if_directive_start_tag] = "fm_if_directive_start_tag",
  [sym__expression] = "_expression",
  [sym_script_start_tag] = "start_tag",
  [sym_style_start_tag] = "start_tag",
  [sym_self_closing_tag] = "self_closing_tag",
  [sym_fm_macro_self_closing_tag] = "fm_macro_self_closing_tag",
  [sym_end_tag] = "end_tag",
  [sym_fm_macro_end_tag] = "fm_macro_end_tag",
  [sym_fm_directive_end_tag] = "fm_directive_end_tag",
  [sym_erroneous_end_tag] = "erroneous_end_tag",
  [sym_attribute] = "attribute",
  [sym_quoted_attribute_value] = "quoted_attribute_value",
  [aux_sym_fragment_repeat1] = "fragment_repeat1",
  [aux_sym_start_tag_repeat1] = "start_tag_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LT_BANG] = anon_sym_LT_BANG,
  [aux_sym_doctype_token1] = aux_sym_doctype_token1,
  [anon_sym_GT] = anon_sym_GT,
  [sym__doctype] = sym__doctype,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_LT_AT] = anon_sym_LT_AT,
  [anon_sym_LT_POUND] = anon_sym_LT_POUND,
  [anon_sym_if] = anon_sym_if,
  [sym_identifier] = sym_identifier,
  [anon_sym_SLASH_GT] = anon_sym_SLASH_GT,
  [anon_sym_LT_SLASH] = anon_sym_LT_SLASH,
  [anon_sym_LT_SLASH_AT] = anon_sym_LT_SLASH_AT,
  [anon_sym_LT_SLASH_POUND] = anon_sym_LT_SLASH_POUND,
  [anon_sym_EQ] = anon_sym_EQ,
  [sym_attribute_name] = sym_attribute_name,
  [sym_attribute_value] = sym_attribute_value,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [aux_sym_quoted_attribute_value_token1] = sym_attribute_value,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_quoted_attribute_value_token2] = sym_attribute_value,
  [sym_text] = sym_text,
  [sym__start_tag_name] = sym__start_tag_name,
  [sym__script_start_tag_name] = sym__start_tag_name,
  [sym__style_start_tag_name] = sym__start_tag_name,
  [sym__end_tag_name] = sym__start_tag_name,
  [sym_erroneous_end_tag_name] = sym_erroneous_end_tag_name,
  [sym__implicit_end_tag] = sym__implicit_end_tag,
  [sym_raw_text] = sym_raw_text,
  [sym_comment] = sym_comment,
  [sym_fragment] = sym_fragment,
  [sym_doctype] = sym_doctype,
  [sym__node] = sym__node,
  [sym_element] = sym_element,
  [sym_fm_macro] = sym_fm_macro,
  [sym_fm_directive] = sym_fm_directive,
  [sym_script_element] = sym_script_element,
  [sym_style_element] = sym_style_element,
  [sym_start_tag] = sym_start_tag,
  [sym_fm_macro_start_tag] = sym_fm_macro_start_tag,
  [sym_fm_directive_start_tag] = sym_fm_directive_start_tag,
  [sym_fm_if_directive_start_tag] = sym_fm_if_directive_start_tag,
  [sym__expression] = sym__expression,
  [sym_script_start_tag] = sym_start_tag,
  [sym_style_start_tag] = sym_start_tag,
  [sym_self_closing_tag] = sym_self_closing_tag,
  [sym_fm_macro_self_closing_tag] = sym_fm_macro_self_closing_tag,
  [sym_end_tag] = sym_end_tag,
  [sym_fm_macro_end_tag] = sym_fm_macro_end_tag,
  [sym_fm_directive_end_tag] = sym_fm_directive_end_tag,
  [sym_erroneous_end_tag] = sym_erroneous_end_tag,
  [sym_attribute] = sym_attribute,
  [sym_quoted_attribute_value] = sym_quoted_attribute_value,
  [aux_sym_fragment_repeat1] = aux_sym_fragment_repeat1,
  [aux_sym_start_tag_repeat1] = aux_sym_start_tag_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LT_BANG] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_doctype_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [sym__doctype] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_AT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_POUND] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_if] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SLASH_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_SLASH_AT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_SLASH_POUND] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_attribute_name] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute_value] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_quoted_attribute_value_token1] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_quoted_attribute_value_token2] = {
    .visible = true,
    .named = true,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [sym__start_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym__script_start_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym__style_start_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym__end_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym_erroneous_end_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym__implicit_end_tag] = {
    .visible = false,
    .named = true,
  },
  [sym_raw_text] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_fragment] = {
    .visible = true,
    .named = true,
  },
  [sym_doctype] = {
    .visible = true,
    .named = true,
  },
  [sym__node] = {
    .visible = false,
    .named = true,
  },
  [sym_element] = {
    .visible = true,
    .named = true,
  },
  [sym_fm_macro] = {
    .visible = true,
    .named = true,
  },
  [sym_fm_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_script_element] = {
    .visible = true,
    .named = true,
  },
  [sym_style_element] = {
    .visible = true,
    .named = true,
  },
  [sym_start_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_fm_macro_start_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_fm_directive_start_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_fm_if_directive_start_tag] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym_script_start_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_style_start_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_self_closing_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_fm_macro_self_closing_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_end_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_fm_macro_end_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_fm_directive_end_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_erroneous_end_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym_quoted_attribute_value] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_fragment_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_start_tag_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 2,
  [5] = 3,
  [6] = 6,
  [7] = 7,
  [8] = 7,
  [9] = 6,
  [10] = 10,
  [11] = 11,
  [12] = 10,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 30,
  [36] = 27,
  [37] = 14,
  [38] = 26,
  [39] = 23,
  [40] = 28,
  [41] = 41,
  [42] = 21,
  [43] = 22,
  [44] = 34,
  [45] = 13,
  [46] = 25,
  [47] = 47,
  [48] = 24,
  [49] = 20,
  [50] = 15,
  [51] = 16,
  [52] = 19,
  [53] = 29,
  [54] = 18,
  [55] = 31,
  [56] = 17,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 57,
  [62] = 59,
  [63] = 63,
  [64] = 63,
  [65] = 58,
  [66] = 60,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 68,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 77,
  [79] = 79,
  [80] = 75,
  [81] = 81,
  [82] = 81,
  [83] = 74,
  [84] = 72,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 89,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 90,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 88,
  [101] = 94,
  [102] = 102,
  [103] = 85,
  [104] = 76,
  [105] = 79,
  [106] = 86,
  [107] = 93,
  [108] = 108,
  [109] = 108,
  [110] = 110,
  [111] = 92,
  [112] = 112,
  [113] = 113,
  [114] = 113,
  [115] = 115,
  [116] = 116,
  [117] = 117,
  [118] = 118,
  [119] = 119,
  [120] = 120,
  [121] = 121,
  [122] = 112,
  [123] = 123,
  [124] = 121,
  [125] = 119,
  [126] = 126,
  [127] = 127,
  [128] = 123,
  [129] = 129,
  [130] = 129,
  [131] = 115,
  [132] = 117,
  [133] = 126,
  [134] = 134,
  [135] = 120,
  [136] = 116,
  [137] = 110,
  [138] = 127,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(19);
      if (lookahead == '"') ADVANCE(43);
      if (lookahead == '\'') ADVANCE(40);
      if (lookahead == '/') ADVANCE(7);
      if (lookahead == '<') ADVANCE(25);
      if (lookahead == '=') ADVANCE(37);
      if (lookahead == '>') ADVANCE(23);
      if (lookahead == 'i') ADVANCE(8);
      if (lookahead == 'D' ||
          lookahead == 'd') ADVANCE(11);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(43);
      if (lookahead == '\'') ADVANCE(40);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(1)
      if (lookahead != 0 &&
          (lookahead < '<' || '>' < lookahead)) ADVANCE(39);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(43);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(44);
      if (lookahead != 0) ADVANCE(45);
      END_STATE();
    case 3:
      if (lookahead == '#') ADVANCE(36);
      END_STATE();
    case 4:
      if (lookahead == '\'') ADVANCE(40);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(41);
      if (lookahead != 0) ADVANCE(42);
      END_STATE();
    case 5:
      if (lookahead == '/') ADVANCE(7);
      if (lookahead == '<') ADVANCE(6);
      if (lookahead == '=') ADVANCE(37);
      if (lookahead == '>') ADVANCE(23);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(5)
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\'') ADVANCE(38);
      END_STATE();
    case 6:
      if (lookahead == '/') ADVANCE(3);
      END_STATE();
    case 7:
      if (lookahead == '>') ADVANCE(32);
      END_STATE();
    case 8:
      if (lookahead == 'f') ADVANCE(29);
      END_STATE();
    case 9:
      if (lookahead == 'C' ||
          lookahead == 'c') ADVANCE(13);
      END_STATE();
    case 10:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(24);
      END_STATE();
    case 11:
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(9);
      END_STATE();
    case 12:
      if (lookahead == 'P' ||
          lookahead == 'p') ADVANCE(10);
      END_STATE();
    case 13:
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(14);
      END_STATE();
    case 14:
      if (lookahead == 'Y' ||
          lookahead == 'y') ADVANCE(12);
      END_STATE();
    case 15:
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(15);
      if (lookahead != 0 &&
          lookahead != '<' &&
          lookahead != '>') ADVANCE(47);
      END_STATE();
    case 16:
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(16)
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(31);
      END_STATE();
    case 17:
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(21);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(22);
      END_STATE();
    case 18:
      if (eof) ADVANCE(19);
      if (lookahead == '<') ADVANCE(26);
      if (lookahead == 'i') ADVANCE(46);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(18)
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(47);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_LT_BANG);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(aux_sym_doctype_token1);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(21);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(22);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(aux_sym_doctype_token1);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(22);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym__doctype);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '!') ADVANCE(20);
      if (lookahead == '#') ADVANCE(28);
      if (lookahead == '/') ADVANCE(33);
      if (lookahead == '@') ADVANCE(27);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '!') ADVANCE(20);
      if (lookahead == '#') ADVANCE(28);
      if (lookahead == '/') ADVANCE(34);
      if (lookahead == '@') ADVANCE(27);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_LT_AT);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_LT_POUND);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_if);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_if);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(15);
      if (lookahead != 0 &&
          lookahead != '<' &&
          lookahead != '>') ADVANCE(47);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_identifier);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(31);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_SLASH_GT);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_LT_SLASH);
      if (lookahead == '#') ADVANCE(36);
      if (lookahead == '@') ADVANCE(35);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_LT_SLASH);
      if (lookahead == '@') ADVANCE(35);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_LT_SLASH_AT);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_LT_SLASH_POUND);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_attribute_name);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '\'' &&
          lookahead != '/' &&
          (lookahead < '<' || '>' < lookahead)) ADVANCE(38);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_attribute_value);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '\'' &&
          (lookahead < '<' || '>' < lookahead)) ADVANCE(39);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(aux_sym_quoted_attribute_value_token1);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(41);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(42);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(aux_sym_quoted_attribute_value_token1);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(42);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(aux_sym_quoted_attribute_value_token2);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(44);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(45);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(aux_sym_quoted_attribute_value_token2);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(45);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'f') ADVANCE(30);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(15);
      if (lookahead != 0 &&
          lookahead != '<' &&
          lookahead != '>') ADVANCE(47);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(15);
      if (lookahead != 0 &&
          lookahead != '<' &&
          lookahead != '>') ADVANCE(47);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 18, .external_lex_state = 2},
  [2] = {.lex_state = 18, .external_lex_state = 3},
  [3] = {.lex_state = 18, .external_lex_state = 3},
  [4] = {.lex_state = 18, .external_lex_state = 3},
  [5] = {.lex_state = 18, .external_lex_state = 3},
  [6] = {.lex_state = 18, .external_lex_state = 3},
  [7] = {.lex_state = 18, .external_lex_state = 3},
  [8] = {.lex_state = 18, .external_lex_state = 3},
  [9] = {.lex_state = 18, .external_lex_state = 3},
  [10] = {.lex_state = 18, .external_lex_state = 3},
  [11] = {.lex_state = 18, .external_lex_state = 2},
  [12] = {.lex_state = 18, .external_lex_state = 2},
  [13] = {.lex_state = 18, .external_lex_state = 3},
  [14] = {.lex_state = 18, .external_lex_state = 3},
  [15] = {.lex_state = 18, .external_lex_state = 3},
  [16] = {.lex_state = 18, .external_lex_state = 3},
  [17] = {.lex_state = 18, .external_lex_state = 3},
  [18] = {.lex_state = 18, .external_lex_state = 3},
  [19] = {.lex_state = 18, .external_lex_state = 3},
  [20] = {.lex_state = 18, .external_lex_state = 3},
  [21] = {.lex_state = 18, .external_lex_state = 3},
  [22] = {.lex_state = 18, .external_lex_state = 3},
  [23] = {.lex_state = 18, .external_lex_state = 3},
  [24] = {.lex_state = 18, .external_lex_state = 3},
  [25] = {.lex_state = 18, .external_lex_state = 3},
  [26] = {.lex_state = 18, .external_lex_state = 3},
  [27] = {.lex_state = 18, .external_lex_state = 3},
  [28] = {.lex_state = 18, .external_lex_state = 3},
  [29] = {.lex_state = 18, .external_lex_state = 3},
  [30] = {.lex_state = 18, .external_lex_state = 3},
  [31] = {.lex_state = 18, .external_lex_state = 3},
  [32] = {.lex_state = 18, .external_lex_state = 3},
  [33] = {.lex_state = 18, .external_lex_state = 3},
  [34] = {.lex_state = 18, .external_lex_state = 3},
  [35] = {.lex_state = 18, .external_lex_state = 2},
  [36] = {.lex_state = 18, .external_lex_state = 2},
  [37] = {.lex_state = 18, .external_lex_state = 2},
  [38] = {.lex_state = 18, .external_lex_state = 2},
  [39] = {.lex_state = 18, .external_lex_state = 2},
  [40] = {.lex_state = 18, .external_lex_state = 2},
  [41] = {.lex_state = 18, .external_lex_state = 3},
  [42] = {.lex_state = 18, .external_lex_state = 2},
  [43] = {.lex_state = 18, .external_lex_state = 2},
  [44] = {.lex_state = 18, .external_lex_state = 2},
  [45] = {.lex_state = 18, .external_lex_state = 2},
  [46] = {.lex_state = 18, .external_lex_state = 2},
  [47] = {.lex_state = 18, .external_lex_state = 3},
  [48] = {.lex_state = 18, .external_lex_state = 2},
  [49] = {.lex_state = 18, .external_lex_state = 2},
  [50] = {.lex_state = 18, .external_lex_state = 2},
  [51] = {.lex_state = 18, .external_lex_state = 2},
  [52] = {.lex_state = 18, .external_lex_state = 2},
  [53] = {.lex_state = 18, .external_lex_state = 2},
  [54] = {.lex_state = 18, .external_lex_state = 2},
  [55] = {.lex_state = 18, .external_lex_state = 2},
  [56] = {.lex_state = 18, .external_lex_state = 2},
  [57] = {.lex_state = 5, .external_lex_state = 4},
  [58] = {.lex_state = 5, .external_lex_state = 4},
  [59] = {.lex_state = 5, .external_lex_state = 4},
  [60] = {.lex_state = 5, .external_lex_state = 4},
  [61] = {.lex_state = 5, .external_lex_state = 4},
  [62] = {.lex_state = 5, .external_lex_state = 4},
  [63] = {.lex_state = 5, .external_lex_state = 4},
  [64] = {.lex_state = 5, .external_lex_state = 4},
  [65] = {.lex_state = 5, .external_lex_state = 4},
  [66] = {.lex_state = 5, .external_lex_state = 2},
  [67] = {.lex_state = 5, .external_lex_state = 2},
  [68] = {.lex_state = 1, .external_lex_state = 2},
  [69] = {.lex_state = 5, .external_lex_state = 2},
  [70] = {.lex_state = 5, .external_lex_state = 2},
  [71] = {.lex_state = 5, .external_lex_state = 2},
  [72] = {.lex_state = 5, .external_lex_state = 4},
  [73] = {.lex_state = 1, .external_lex_state = 2},
  [74] = {.lex_state = 18, .external_lex_state = 5},
  [75] = {.lex_state = 18, .external_lex_state = 5},
  [76] = {.lex_state = 5, .external_lex_state = 4},
  [77] = {.lex_state = 0, .external_lex_state = 6},
  [78] = {.lex_state = 0, .external_lex_state = 6},
  [79] = {.lex_state = 5, .external_lex_state = 4},
  [80] = {.lex_state = 18, .external_lex_state = 5},
  [81] = {.lex_state = 5, .external_lex_state = 3},
  [82] = {.lex_state = 5, .external_lex_state = 3},
  [83] = {.lex_state = 18, .external_lex_state = 5},
  [84] = {.lex_state = 5, .external_lex_state = 2},
  [85] = {.lex_state = 5, .external_lex_state = 4},
  [86] = {.lex_state = 16, .external_lex_state = 2},
  [87] = {.lex_state = 0, .external_lex_state = 2},
  [88] = {.lex_state = 18, .external_lex_state = 2},
  [89] = {.lex_state = 0, .external_lex_state = 7},
  [90] = {.lex_state = 4, .external_lex_state = 2},
  [91] = {.lex_state = 0, .external_lex_state = 7},
  [92] = {.lex_state = 5, .external_lex_state = 3},
  [93] = {.lex_state = 2, .external_lex_state = 2},
  [94] = {.lex_state = 18, .external_lex_state = 2},
  [95] = {.lex_state = 4, .external_lex_state = 2},
  [96] = {.lex_state = 18, .external_lex_state = 5},
  [97] = {.lex_state = 18, .external_lex_state = 5},
  [98] = {.lex_state = 18, .external_lex_state = 5},
  [99] = {.lex_state = 18, .external_lex_state = 5},
  [100] = {.lex_state = 18, .external_lex_state = 2},
  [101] = {.lex_state = 18, .external_lex_state = 2},
  [102] = {.lex_state = 5, .external_lex_state = 3},
  [103] = {.lex_state = 5, .external_lex_state = 2},
  [104] = {.lex_state = 5, .external_lex_state = 2},
  [105] = {.lex_state = 5, .external_lex_state = 2},
  [106] = {.lex_state = 16, .external_lex_state = 2},
  [107] = {.lex_state = 2, .external_lex_state = 2},
  [108] = {.lex_state = 0, .external_lex_state = 2},
  [109] = {.lex_state = 0, .external_lex_state = 2},
  [110] = {.lex_state = 0, .external_lex_state = 8},
  [111] = {.lex_state = 0, .external_lex_state = 2},
  [112] = {.lex_state = 0, .external_lex_state = 2},
  [113] = {.lex_state = 0, .external_lex_state = 2},
  [114] = {.lex_state = 0, .external_lex_state = 2},
  [115] = {.lex_state = 0, .external_lex_state = 9},
  [116] = {.lex_state = 0, .external_lex_state = 2},
  [117] = {.lex_state = 0, .external_lex_state = 10},
  [118] = {.lex_state = 0, .external_lex_state = 2},
  [119] = {.lex_state = 0, .external_lex_state = 2},
  [120] = {.lex_state = 0, .external_lex_state = 8},
  [121] = {.lex_state = 0, .external_lex_state = 2},
  [122] = {.lex_state = 0, .external_lex_state = 2},
  [123] = {.lex_state = 0, .external_lex_state = 2},
  [124] = {.lex_state = 0, .external_lex_state = 2},
  [125] = {.lex_state = 0, .external_lex_state = 2},
  [126] = {.lex_state = 17, .external_lex_state = 2},
  [127] = {.lex_state = 0, .external_lex_state = 2},
  [128] = {.lex_state = 0, .external_lex_state = 2},
  [129] = {.lex_state = 0, .external_lex_state = 2},
  [130] = {.lex_state = 0, .external_lex_state = 2},
  [131] = {.lex_state = 0, .external_lex_state = 9},
  [132] = {.lex_state = 0, .external_lex_state = 10},
  [133] = {.lex_state = 17, .external_lex_state = 2},
  [134] = {.lex_state = 0, .external_lex_state = 2},
  [135] = {.lex_state = 0, .external_lex_state = 8},
  [136] = {.lex_state = 0, .external_lex_state = 2},
  [137] = {.lex_state = 0, .external_lex_state = 8},
  [138] = {.lex_state = 0, .external_lex_state = 2},
};

enum {
  ts_external_token__start_tag_name = 0,
  ts_external_token__script_start_tag_name = 1,
  ts_external_token__style_start_tag_name = 2,
  ts_external_token__end_tag_name = 3,
  ts_external_token_erroneous_end_tag_name = 4,
  ts_external_token_SLASH_GT = 5,
  ts_external_token__implicit_end_tag = 6,
  ts_external_token_raw_text = 7,
  ts_external_token_comment = 8,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token__start_tag_name] = sym__start_tag_name,
  [ts_external_token__script_start_tag_name] = sym__script_start_tag_name,
  [ts_external_token__style_start_tag_name] = sym__style_start_tag_name,
  [ts_external_token__end_tag_name] = sym__end_tag_name,
  [ts_external_token_erroneous_end_tag_name] = sym_erroneous_end_tag_name,
  [ts_external_token_SLASH_GT] = anon_sym_SLASH_GT,
  [ts_external_token__implicit_end_tag] = sym__implicit_end_tag,
  [ts_external_token_raw_text] = sym_raw_text,
  [ts_external_token_comment] = sym_comment,
};

static const bool ts_external_scanner_states[11][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token__start_tag_name] = true,
    [ts_external_token__script_start_tag_name] = true,
    [ts_external_token__style_start_tag_name] = true,
    [ts_external_token__end_tag_name] = true,
    [ts_external_token_erroneous_end_tag_name] = true,
    [ts_external_token_SLASH_GT] = true,
    [ts_external_token__implicit_end_tag] = true,
    [ts_external_token_raw_text] = true,
    [ts_external_token_comment] = true,
  },
  [2] = {
    [ts_external_token_comment] = true,
  },
  [3] = {
    [ts_external_token__implicit_end_tag] = true,
    [ts_external_token_comment] = true,
  },
  [4] = {
    [ts_external_token_SLASH_GT] = true,
    [ts_external_token_comment] = true,
  },
  [5] = {
    [ts_external_token_raw_text] = true,
    [ts_external_token_comment] = true,
  },
  [6] = {
    [ts_external_token__start_tag_name] = true,
    [ts_external_token__script_start_tag_name] = true,
    [ts_external_token__style_start_tag_name] = true,
    [ts_external_token_comment] = true,
  },
  [7] = {
    [ts_external_token__end_tag_name] = true,
    [ts_external_token_erroneous_end_tag_name] = true,
    [ts_external_token_comment] = true,
  },
  [8] = {
    [ts_external_token__end_tag_name] = true,
    [ts_external_token_comment] = true,
  },
  [9] = {
    [ts_external_token__start_tag_name] = true,
    [ts_external_token_comment] = true,
  },
  [10] = {
    [ts_external_token_erroneous_end_tag_name] = true,
    [ts_external_token_comment] = true,
  },
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LT_BANG] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [sym__doctype] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_LT_AT] = ACTIONS(1),
    [anon_sym_LT_POUND] = ACTIONS(1),
    [anon_sym_if] = ACTIONS(1),
    [anon_sym_SLASH_GT] = ACTIONS(1),
    [anon_sym_LT_SLASH] = ACTIONS(1),
    [anon_sym_LT_SLASH_AT] = ACTIONS(1),
    [anon_sym_LT_SLASH_POUND] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [sym__start_tag_name] = ACTIONS(1),
    [sym__script_start_tag_name] = ACTIONS(1),
    [sym__style_start_tag_name] = ACTIONS(1),
    [sym__end_tag_name] = ACTIONS(1),
    [sym_erroneous_end_tag_name] = ACTIONS(1),
    [sym__implicit_end_tag] = ACTIONS(1),
    [sym_raw_text] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
  },
  [1] = {
    [sym_fragment] = STATE(118),
    [sym_doctype] = STATE(11),
    [sym__node] = STATE(11),
    [sym_element] = STATE(11),
    [sym_fm_macro] = STATE(11),
    [sym_fm_directive] = STATE(11),
    [sym_script_element] = STATE(11),
    [sym_style_element] = STATE(11),
    [sym_start_tag] = STATE(8),
    [sym_fm_macro_start_tag] = STATE(5),
    [sym_fm_directive_start_tag] = STATE(82),
    [sym_fm_if_directive_start_tag] = STATE(82),
    [sym_script_start_tag] = STATE(83),
    [sym_style_start_tag] = STATE(75),
    [sym_self_closing_tag] = STATE(55),
    [sym_fm_macro_self_closing_tag] = STATE(53),
    [sym_erroneous_end_tag] = STATE(11),
    [aux_sym_fragment_repeat1] = STATE(11),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_LT_BANG] = ACTIONS(7),
    [anon_sym_LT] = ACTIONS(9),
    [anon_sym_LT_AT] = ACTIONS(11),
    [anon_sym_LT_POUND] = ACTIONS(13),
    [anon_sym_if] = ACTIONS(15),
    [anon_sym_LT_SLASH] = ACTIONS(17),
    [sym_text] = ACTIONS(19),
    [sym_comment] = ACTIONS(3),
  },
  [2] = {
    [sym_doctype] = STATE(10),
    [sym__node] = STATE(10),
    [sym_element] = STATE(10),
    [sym_fm_macro] = STATE(10),
    [sym_fm_directive] = STATE(10),
    [sym_script_element] = STATE(10),
    [sym_style_element] = STATE(10),
    [sym_start_tag] = STATE(7),
    [sym_fm_macro_start_tag] = STATE(3),
    [sym_fm_directive_start_tag] = STATE(81),
    [sym_fm_if_directive_start_tag] = STATE(81),
    [sym_script_start_tag] = STATE(74),
    [sym_style_start_tag] = STATE(80),
    [sym_self_closing_tag] = STATE(31),
    [sym_fm_macro_self_closing_tag] = STATE(29),
    [sym_fm_macro_end_tag] = STATE(17),
    [sym_erroneous_end_tag] = STATE(10),
    [aux_sym_fragment_repeat1] = STATE(10),
    [anon_sym_LT_BANG] = ACTIONS(21),
    [anon_sym_LT] = ACTIONS(23),
    [anon_sym_LT_AT] = ACTIONS(25),
    [anon_sym_LT_POUND] = ACTIONS(13),
    [anon_sym_if] = ACTIONS(15),
    [anon_sym_LT_SLASH] = ACTIONS(27),
    [anon_sym_LT_SLASH_AT] = ACTIONS(29),
    [sym_text] = ACTIONS(31),
    [sym__implicit_end_tag] = ACTIONS(33),
    [sym_comment] = ACTIONS(3),
  },
  [3] = {
    [sym_doctype] = STATE(2),
    [sym__node] = STATE(2),
    [sym_element] = STATE(2),
    [sym_fm_macro] = STATE(2),
    [sym_fm_directive] = STATE(2),
    [sym_script_element] = STATE(2),
    [sym_style_element] = STATE(2),
    [sym_start_tag] = STATE(7),
    [sym_fm_macro_start_tag] = STATE(3),
    [sym_fm_directive_start_tag] = STATE(81),
    [sym_fm_if_directive_start_tag] = STATE(81),
    [sym_script_start_tag] = STATE(74),
    [sym_style_start_tag] = STATE(80),
    [sym_self_closing_tag] = STATE(31),
    [sym_fm_macro_self_closing_tag] = STATE(29),
    [sym_fm_macro_end_tag] = STATE(26),
    [sym_erroneous_end_tag] = STATE(2),
    [aux_sym_fragment_repeat1] = STATE(2),
    [anon_sym_LT_BANG] = ACTIONS(21),
    [anon_sym_LT] = ACTIONS(23),
    [anon_sym_LT_AT] = ACTIONS(25),
    [anon_sym_LT_POUND] = ACTIONS(13),
    [anon_sym_if] = ACTIONS(15),
    [anon_sym_LT_SLASH] = ACTIONS(27),
    [anon_sym_LT_SLASH_AT] = ACTIONS(29),
    [sym_text] = ACTIONS(35),
    [sym__implicit_end_tag] = ACTIONS(37),
    [sym_comment] = ACTIONS(3),
  },
  [4] = {
    [sym_doctype] = STATE(10),
    [sym__node] = STATE(10),
    [sym_element] = STATE(10),
    [sym_fm_macro] = STATE(10),
    [sym_fm_directive] = STATE(10),
    [sym_script_element] = STATE(10),
    [sym_style_element] = STATE(10),
    [sym_start_tag] = STATE(7),
    [sym_fm_macro_start_tag] = STATE(3),
    [sym_fm_directive_start_tag] = STATE(81),
    [sym_fm_if_directive_start_tag] = STATE(81),
    [sym_script_start_tag] = STATE(74),
    [sym_style_start_tag] = STATE(80),
    [sym_self_closing_tag] = STATE(31),
    [sym_fm_macro_self_closing_tag] = STATE(29),
    [sym_fm_macro_end_tag] = STATE(56),
    [sym_erroneous_end_tag] = STATE(10),
    [aux_sym_fragment_repeat1] = STATE(10),
    [anon_sym_LT_BANG] = ACTIONS(21),
    [anon_sym_LT] = ACTIONS(23),
    [anon_sym_LT_AT] = ACTIONS(25),
    [anon_sym_LT_POUND] = ACTIONS(13),
    [anon_sym_if] = ACTIONS(15),
    [anon_sym_LT_SLASH] = ACTIONS(27),
    [anon_sym_LT_SLASH_AT] = ACTIONS(39),
    [sym_text] = ACTIONS(31),
    [sym__implicit_end_tag] = ACTIONS(41),
    [sym_comment] = ACTIONS(3),
  },
  [5] = {
    [sym_doctype] = STATE(4),
    [sym__node] = STATE(4),
    [sym_element] = STATE(4),
    [sym_fm_macro] = STATE(4),
    [sym_fm_directive] = STATE(4),
    [sym_script_element] = STATE(4),
    [sym_style_element] = STATE(4),
    [sym_start_tag] = STATE(7),
    [sym_fm_macro_start_tag] = STATE(3),
    [sym_fm_directive_start_tag] = STATE(81),
    [sym_fm_if_directive_start_tag] = STATE(81),
    [sym_script_start_tag] = STATE(74),
    [sym_style_start_tag] = STATE(80),
    [sym_self_closing_tag] = STATE(31),
    [sym_fm_macro_self_closing_tag] = STATE(29),
    [sym_fm_macro_end_tag] = STATE(38),
    [sym_erroneous_end_tag] = STATE(4),
    [aux_sym_fragment_repeat1] = STATE(4),
    [anon_sym_LT_BANG] = ACTIONS(21),
    [anon_sym_LT] = ACTIONS(23),
    [anon_sym_LT_AT] = ACTIONS(25),
    [anon_sym_LT_POUND] = ACTIONS(13),
    [anon_sym_if] = ACTIONS(15),
    [anon_sym_LT_SLASH] = ACTIONS(27),
    [anon_sym_LT_SLASH_AT] = ACTIONS(39),
    [sym_text] = ACTIONS(43),
    [sym__implicit_end_tag] = ACTIONS(45),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 18,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      anon_sym_LT_POUND,
    ACTIONS(15), 1,
      anon_sym_if,
    ACTIONS(21), 1,
      anon_sym_LT_BANG,
    ACTIONS(23), 1,
      anon_sym_LT,
    ACTIONS(25), 1,
      anon_sym_LT_AT,
    ACTIONS(31), 1,
      sym_text,
    ACTIONS(47), 1,
      anon_sym_LT_SLASH,
    ACTIONS(49), 1,
      sym__implicit_end_tag,
    STATE(3), 1,
      sym_fm_macro_start_tag,
    STATE(7), 1,
      sym_start_tag,
    STATE(18), 1,
      sym_end_tag,
    STATE(29), 1,
      sym_fm_macro_self_closing_tag,
    STATE(31), 1,
      sym_self_closing_tag,
    STATE(74), 1,
      sym_script_start_tag,
    STATE(80), 1,
      sym_style_start_tag,
    STATE(81), 2,
      sym_fm_directive_start_tag,
      sym_fm_if_directive_start_tag,
    STATE(10), 9,
      sym_doctype,
      sym__node,
      sym_element,
      sym_fm_macro,
      sym_fm_directive,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
      aux_sym_fragment_repeat1,
  [64] = 18,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      anon_sym_LT_POUND,
    ACTIONS(15), 1,
      anon_sym_if,
    ACTIONS(21), 1,
      anon_sym_LT_BANG,
    ACTIONS(23), 1,
      anon_sym_LT,
    ACTIONS(25), 1,
      anon_sym_LT_AT,
    ACTIONS(47), 1,
      anon_sym_LT_SLASH,
    ACTIONS(51), 1,
      sym_text,
    ACTIONS(53), 1,
      sym__implicit_end_tag,
    STATE(3), 1,
      sym_fm_macro_start_tag,
    STATE(7), 1,
      sym_start_tag,
    STATE(28), 1,
      sym_end_tag,
    STATE(29), 1,
      sym_fm_macro_self_closing_tag,
    STATE(31), 1,
      sym_self_closing_tag,
    STATE(74), 1,
      sym_script_start_tag,
    STATE(80), 1,
      sym_style_start_tag,
    STATE(81), 2,
      sym_fm_directive_start_tag,
      sym_fm_if_directive_start_tag,
    STATE(6), 9,
      sym_doctype,
      sym__node,
      sym_element,
      sym_fm_macro,
      sym_fm_directive,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
      aux_sym_fragment_repeat1,
  [128] = 18,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      anon_sym_LT_POUND,
    ACTIONS(15), 1,
      anon_sym_if,
    ACTIONS(21), 1,
      anon_sym_LT_BANG,
    ACTIONS(23), 1,
      anon_sym_LT,
    ACTIONS(25), 1,
      anon_sym_LT_AT,
    ACTIONS(55), 1,
      anon_sym_LT_SLASH,
    ACTIONS(57), 1,
      sym_text,
    ACTIONS(59), 1,
      sym__implicit_end_tag,
    STATE(3), 1,
      sym_fm_macro_start_tag,
    STATE(7), 1,
      sym_start_tag,
    STATE(29), 1,
      sym_fm_macro_self_closing_tag,
    STATE(31), 1,
      sym_self_closing_tag,
    STATE(40), 1,
      sym_end_tag,
    STATE(74), 1,
      sym_script_start_tag,
    STATE(80), 1,
      sym_style_start_tag,
    STATE(81), 2,
      sym_fm_directive_start_tag,
      sym_fm_if_directive_start_tag,
    STATE(9), 9,
      sym_doctype,
      sym__node,
      sym_element,
      sym_fm_macro,
      sym_fm_directive,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
      aux_sym_fragment_repeat1,
  [192] = 18,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 1,
      anon_sym_LT_POUND,
    ACTIONS(15), 1,
      anon_sym_if,
    ACTIONS(21), 1,
      anon_sym_LT_BANG,
    ACTIONS(23), 1,
      anon_sym_LT,
    ACTIONS(25), 1,
      anon_sym_LT_AT,
    ACTIONS(31), 1,
      sym_text,
    ACTIONS(55), 1,
      anon_sym_LT_SLASH,
    ACTIONS(61), 1,
      sym__implicit_end_tag,
    STATE(3), 1,
      sym_fm_macro_start_tag,
    STATE(7), 1,
      sym_start_tag,
    STATE(29), 1,
      sym_fm_macro_self_closing_tag,
    STATE(31), 1,
      sym_self_closing_tag,
    STATE(54), 1,
      sym_end_tag,
    STATE(74), 1,
      sym_script_start_tag,
    STATE(80), 1,
      sym_style_start_tag,
    STATE(81), 2,
      sym_fm_directive_start_tag,
      sym_fm_if_directive_start_tag,
    STATE(10), 9,
      sym_doctype,
      sym__node,
      sym_element,
      sym_fm_macro,
      sym_fm_directive,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
      aux_sym_fragment_repeat1,
  [256] = 17,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(63), 1,
      anon_sym_LT_BANG,
    ACTIONS(66), 1,
      anon_sym_LT,
    ACTIONS(69), 1,
      anon_sym_LT_AT,
    ACTIONS(72), 1,
      anon_sym_LT_POUND,
    ACTIONS(75), 1,
      anon_sym_if,
    ACTIONS(78), 1,
      anon_sym_LT_SLASH,
    ACTIONS(83), 1,
      sym_text,
    STATE(3), 1,
      sym_fm_macro_start_tag,
    STATE(7), 1,
      sym_start_tag,
    STATE(29), 1,
      sym_fm_macro_self_closing_tag,
    STATE(31), 1,
      sym_self_closing_tag,
    STATE(74), 1,
      sym_script_start_tag,
    STATE(80), 1,
      sym_style_start_tag,
    ACTIONS(81), 2,
      sym__implicit_end_tag,
      anon_sym_LT_SLASH_AT,
    STATE(81), 2,
      sym_fm_directive_start_tag,
      sym_fm_if_directive_start_tag,
    STATE(10), 9,
      sym_doctype,
      sym__node,
      sym_element,
      sym_fm_macro,
      sym_fm_directive,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
      aux_sym_fragment_repeat1,
  [318] = 17,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LT_BANG,
    ACTIONS(9), 1,
      anon_sym_LT,
    ACTIONS(11), 1,
      anon_sym_LT_AT,
    ACTIONS(13), 1,
      anon_sym_LT_POUND,
    ACTIONS(15), 1,
      anon_sym_if,
    ACTIONS(17), 1,
      anon_sym_LT_SLASH,
    ACTIONS(86), 1,
      ts_builtin_sym_end,
    ACTIONS(88), 1,
      sym_text,
    STATE(5), 1,
      sym_fm_macro_start_tag,
    STATE(8), 1,
      sym_start_tag,
    STATE(53), 1,
      sym_fm_macro_self_closing_tag,
    STATE(55), 1,
      sym_self_closing_tag,
    STATE(75), 1,
      sym_style_start_tag,
    STATE(83), 1,
      sym_script_start_tag,
    STATE(82), 2,
      sym_fm_directive_start_tag,
      sym_fm_if_directive_start_tag,
    STATE(12), 9,
      sym_doctype,
      sym__node,
      sym_element,
      sym_fm_macro,
      sym_fm_directive,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
      aux_sym_fragment_repeat1,
  [379] = 17,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(72), 1,
      anon_sym_LT_POUND,
    ACTIONS(75), 1,
      anon_sym_if,
    ACTIONS(81), 1,
      ts_builtin_sym_end,
    ACTIONS(90), 1,
      anon_sym_LT_BANG,
    ACTIONS(93), 1,
      anon_sym_LT,
    ACTIONS(96), 1,
      anon_sym_LT_AT,
    ACTIONS(99), 1,
      anon_sym_LT_SLASH,
    ACTIONS(102), 1,
      sym_text,
    STATE(5), 1,
      sym_fm_macro_start_tag,
    STATE(8), 1,
      sym_start_tag,
    STATE(53), 1,
      sym_fm_macro_self_closing_tag,
    STATE(55), 1,
      sym_self_closing_tag,
    STATE(75), 1,
      sym_style_start_tag,
    STATE(83), 1,
      sym_script_start_tag,
    STATE(82), 2,
      sym_fm_directive_start_tag,
      sym_fm_if_directive_start_tag,
    STATE(12), 9,
      sym_doctype,
      sym__node,
      sym_element,
      sym_fm_macro,
      sym_fm_directive,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
      aux_sym_fragment_repeat1,
  [440] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(107), 4,
      anon_sym_LT,
      anon_sym_if,
      anon_sym_LT_SLASH,
      sym_text,
    ACTIONS(105), 5,
      sym__implicit_end_tag,
      anon_sym_LT_BANG,
      anon_sym_LT_AT,
      anon_sym_LT_POUND,
      anon_sym_LT_SLASH_AT,
  [457] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(111), 4,
      anon_sym_LT,
      anon_sym_if,
      anon_sym_LT_SLASH,
      sym_text,
    ACTIONS(109), 5,
      sym__implicit_end_tag,
      anon_sym_LT_BANG,
      anon_sym_LT_AT,
      anon_sym_LT_POUND,
      anon_sym_LT_SLASH_AT,
  [474] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(115), 4,
      anon_sym_LT,
      anon_sym_if,
      anon_sym_LT_SLASH,
      sym_text,
    ACTIONS(113), 5,
      sym__implicit_end_tag,
      anon_sym_LT_BANG,
      anon_sym_LT_AT,
      anon_sym_LT_POUND,
      anon_sym_LT_SLASH_AT,
  [491] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(119), 4,
      anon_sym_LT,
      anon_sym_if,
      anon_sym_LT_SLASH,
      sym_text,
    ACTIONS(117), 5,
      sym__implicit_end_tag,
      anon_sym_LT_BANG,
      anon_sym_LT_AT,
      anon_sym_LT_POUND,
      anon_sym_LT_SLASH_AT,
  [508] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(123), 4,
      anon_sym_LT,
      anon_sym_if,
      anon_sym_LT_SLASH,
      sym_text,
    ACTIONS(121), 5,
      sym__implicit_end_tag,
      anon_sym_LT_BANG,
      anon_sym_LT_AT,
      anon_sym_LT_POUND,
      anon_sym_LT_SLASH_AT,
  [525] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(127), 4,
      anon_sym_LT,
      anon_sym_if,
      anon_sym_LT_SLASH,
      sym_text,
    ACTIONS(125), 5,
      sym__implicit_end_tag,
      anon_sym_LT_BANG,
      anon_sym_LT_AT,
      anon_sym_LT_POUND,
      anon_sym_LT_SLASH_AT,
  [542] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(131), 4,
      anon_sym_LT,
      anon_sym_if,
      anon_sym_LT_SLASH,
      sym_text,
    ACTIONS(129), 5,
      sym__implicit_end_tag,
      anon_sym_LT_BANG,
      anon_sym_LT_AT,
      anon_sym_LT_POUND,
      anon_sym_LT_SLASH_AT,
  [559] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(135), 4,
      anon_sym_LT,
      anon_sym_if,
      anon_sym_LT_SLASH,
      sym_text,
    ACTIONS(133), 5,
      sym__implicit_end_tag,
      anon_sym_LT_BANG,
      anon_sym_LT_AT,
      anon_sym_LT_POUND,
      anon_sym_LT_SLASH_AT,
  [576] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(139), 4,
      anon_sym_LT,
      anon_sym_if,
      anon_sym_LT_SLASH,
      sym_text,
    ACTIONS(137), 5,
      sym__implicit_end_tag,
      anon_sym_LT_BANG,
      anon_sym_LT_AT,
      anon_sym_LT_POUND,
      anon_sym_LT_SLASH_AT,
  [593] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(143), 4,
      anon_sym_LT,
      anon_sym_if,
      anon_sym_LT_SLASH,
      sym_text,
    ACTIONS(141), 5,
      sym__implicit_end_tag,
      anon_sym_LT_BANG,
      anon_sym_LT_AT,
      anon_sym_LT_POUND,
      anon_sym_LT_SLASH_AT,
  [610] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(147), 4,
      anon_sym_LT,
      anon_sym_if,
      anon_sym_LT_SLASH,
      sym_text,
    ACTIONS(145), 5,
      sym__implicit_end_tag,
      anon_sym_LT_BANG,
      anon_sym_LT_AT,
      anon_sym_LT_POUND,
      anon_sym_LT_SLASH_AT,
  [627] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(151), 4,
      anon_sym_LT,
      anon_sym_if,
      anon_sym_LT_SLASH,
      sym_text,
    ACTIONS(149), 5,
      sym__implicit_end_tag,
      anon_sym_LT_BANG,
      anon_sym_LT_AT,
      anon_sym_LT_POUND,
      anon_sym_LT_SLASH_AT,
  [644] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(155), 4,
      anon_sym_LT,
      anon_sym_if,
      anon_sym_LT_SLASH,
      sym_text,
    ACTIONS(153), 5,
      sym__implicit_end_tag,
      anon_sym_LT_BANG,
      anon_sym_LT_AT,
      anon_sym_LT_POUND,
      anon_sym_LT_SLASH_AT,
  [661] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(159), 4,
      anon_sym_LT,
      anon_sym_if,
      anon_sym_LT_SLASH,
      sym_text,
    ACTIONS(157), 5,
      sym__implicit_end_tag,
      anon_sym_LT_BANG,
      anon_sym_LT_AT,
      anon_sym_LT_POUND,
      anon_sym_LT_SLASH_AT,
  [678] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(163), 4,
      anon_sym_LT,
      anon_sym_if,
      anon_sym_LT_SLASH,
      sym_text,
    ACTIONS(161), 5,
      sym__implicit_end_tag,
      anon_sym_LT_BANG,
      anon_sym_LT_AT,
      anon_sym_LT_POUND,
      anon_sym_LT_SLASH_AT,
  [695] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(167), 4,
      anon_sym_LT,
      anon_sym_if,
      anon_sym_LT_SLASH,
      sym_text,
    ACTIONS(165), 5,
      sym__implicit_end_tag,
      anon_sym_LT_BANG,
      anon_sym_LT_AT,
      anon_sym_LT_POUND,
      anon_sym_LT_SLASH_AT,
  [712] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(171), 4,
      anon_sym_LT,
      anon_sym_if,
      anon_sym_LT_SLASH,
      sym_text,
    ACTIONS(169), 5,
      sym__implicit_end_tag,
      anon_sym_LT_BANG,
      anon_sym_LT_AT,
      anon_sym_LT_POUND,
      anon_sym_LT_SLASH_AT,
  [729] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(175), 4,
      anon_sym_LT,
      anon_sym_if,
      anon_sym_LT_SLASH,
      sym_text,
    ACTIONS(173), 5,
      sym__implicit_end_tag,
      anon_sym_LT_BANG,
      anon_sym_LT_AT,
      anon_sym_LT_POUND,
      anon_sym_LT_SLASH_AT,
  [746] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(179), 4,
      anon_sym_LT,
      anon_sym_if,
      anon_sym_LT_SLASH,
      sym_text,
    ACTIONS(177), 5,
      sym__implicit_end_tag,
      anon_sym_LT_BANG,
      anon_sym_LT_AT,
      anon_sym_LT_POUND,
      anon_sym_LT_SLASH_AT,
  [763] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(183), 4,
      anon_sym_LT,
      anon_sym_if,
      anon_sym_LT_SLASH,
      sym_text,
    ACTIONS(181), 5,
      sym__implicit_end_tag,
      anon_sym_LT_BANG,
      anon_sym_LT_AT,
      anon_sym_LT_POUND,
      anon_sym_LT_SLASH_AT,
  [780] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(187), 4,
      anon_sym_LT,
      anon_sym_if,
      anon_sym_LT_SLASH,
      sym_text,
    ACTIONS(185), 5,
      sym__implicit_end_tag,
      anon_sym_LT_BANG,
      anon_sym_LT_AT,
      anon_sym_LT_POUND,
      anon_sym_LT_SLASH_AT,
  [797] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(191), 4,
      anon_sym_LT,
      anon_sym_if,
      anon_sym_LT_SLASH,
      sym_text,
    ACTIONS(189), 5,
      sym__implicit_end_tag,
      anon_sym_LT_BANG,
      anon_sym_LT_AT,
      anon_sym_LT_POUND,
      anon_sym_LT_SLASH_AT,
  [814] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(175), 3,
      anon_sym_LT,
      anon_sym_if,
      sym_text,
    ACTIONS(173), 5,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_AT,
      anon_sym_LT_POUND,
      anon_sym_LT_SLASH,
  [830] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(163), 3,
      anon_sym_LT,
      anon_sym_if,
      sym_text,
    ACTIONS(161), 5,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_AT,
      anon_sym_LT_POUND,
      anon_sym_LT_SLASH,
  [846] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(111), 3,
      anon_sym_LT,
      anon_sym_if,
      sym_text,
    ACTIONS(109), 5,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_AT,
      anon_sym_LT_POUND,
      anon_sym_LT_SLASH,
  [862] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(159), 3,
      anon_sym_LT,
      anon_sym_if,
      sym_text,
    ACTIONS(157), 5,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_AT,
      anon_sym_LT_POUND,
      anon_sym_LT_SLASH,
  [878] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(147), 3,
      anon_sym_LT,
      anon_sym_if,
      sym_text,
    ACTIONS(145), 5,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_AT,
      anon_sym_LT_POUND,
      anon_sym_LT_SLASH,
  [894] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(167), 3,
      anon_sym_LT,
      anon_sym_if,
      sym_text,
    ACTIONS(165), 5,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_AT,
      anon_sym_LT_POUND,
      anon_sym_LT_SLASH,
  [910] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(195), 3,
      anon_sym_LT,
      anon_sym_if,
      sym_text,
    ACTIONS(193), 5,
      sym__implicit_end_tag,
      anon_sym_LT_BANG,
      anon_sym_LT_AT,
      anon_sym_LT_POUND,
      anon_sym_LT_SLASH,
  [926] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(139), 3,
      anon_sym_LT,
      anon_sym_if,
      sym_text,
    ACTIONS(137), 5,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_AT,
      anon_sym_LT_POUND,
      anon_sym_LT_SLASH,
  [942] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(143), 3,
      anon_sym_LT,
      anon_sym_if,
      sym_text,
    ACTIONS(141), 5,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_AT,
      anon_sym_LT_POUND,
      anon_sym_LT_SLASH,
  [958] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(191), 3,
      anon_sym_LT,
      anon_sym_if,
      sym_text,
    ACTIONS(189), 5,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_AT,
      anon_sym_LT_POUND,
      anon_sym_LT_SLASH,
  [974] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(107), 3,
      anon_sym_LT,
      anon_sym_if,
      sym_text,
    ACTIONS(105), 5,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_AT,
      anon_sym_LT_POUND,
      anon_sym_LT_SLASH,
  [990] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(155), 3,
      anon_sym_LT,
      anon_sym_if,
      sym_text,
    ACTIONS(153), 5,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_AT,
      anon_sym_LT_POUND,
      anon_sym_LT_SLASH,
  [1006] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(199), 3,
      anon_sym_LT,
      anon_sym_if,
      sym_text,
    ACTIONS(197), 5,
      sym__implicit_end_tag,
      anon_sym_LT_BANG,
      anon_sym_LT_AT,
      anon_sym_LT_POUND,
      anon_sym_LT_SLASH,
  [1022] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(151), 3,
      anon_sym_LT,
      anon_sym_if,
      sym_text,
    ACTIONS(149), 5,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_AT,
      anon_sym_LT_POUND,
      anon_sym_LT_SLASH,
  [1038] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(135), 3,
      anon_sym_LT,
      anon_sym_if,
      sym_text,
    ACTIONS(133), 5,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_AT,
      anon_sym_LT_POUND,
      anon_sym_LT_SLASH,
  [1054] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(115), 3,
      anon_sym_LT,
      anon_sym_if,
      sym_text,
    ACTIONS(113), 5,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_AT,
      anon_sym_LT_POUND,
      anon_sym_LT_SLASH,
  [1070] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(119), 3,
      anon_sym_LT,
      anon_sym_if,
      sym_text,
    ACTIONS(117), 5,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_AT,
      anon_sym_LT_POUND,
      anon_sym_LT_SLASH,
  [1086] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(131), 3,
      anon_sym_LT,
      anon_sym_if,
      sym_text,
    ACTIONS(129), 5,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_AT,
      anon_sym_LT_POUND,
      anon_sym_LT_SLASH,
  [1102] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(171), 3,
      anon_sym_LT,
      anon_sym_if,
      sym_text,
    ACTIONS(169), 5,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_AT,
      anon_sym_LT_POUND,
      anon_sym_LT_SLASH,
  [1118] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(127), 3,
      anon_sym_LT,
      anon_sym_if,
      sym_text,
    ACTIONS(125), 5,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_AT,
      anon_sym_LT_POUND,
      anon_sym_LT_SLASH,
  [1134] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(179), 3,
      anon_sym_LT,
      anon_sym_if,
      sym_text,
    ACTIONS(177), 5,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_AT,
      anon_sym_LT_POUND,
      anon_sym_LT_SLASH,
  [1150] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(123), 3,
      anon_sym_LT,
      anon_sym_if,
      sym_text,
    ACTIONS(121), 5,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_AT,
      anon_sym_LT_POUND,
      anon_sym_LT_SLASH,
  [1166] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(201), 1,
      anon_sym_GT,
    ACTIONS(203), 1,
      anon_sym_SLASH_GT,
    ACTIONS(205), 1,
      sym_attribute_name,
    STATE(63), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [1183] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(205), 1,
      sym_attribute_name,
    ACTIONS(207), 1,
      anon_sym_GT,
    ACTIONS(209), 1,
      anon_sym_SLASH_GT,
    STATE(60), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [1200] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(205), 1,
      sym_attribute_name,
    ACTIONS(211), 1,
      anon_sym_GT,
    ACTIONS(213), 1,
      anon_sym_SLASH_GT,
    STATE(65), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [1217] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(217), 1,
      sym_attribute_name,
    ACTIONS(215), 2,
      anon_sym_GT,
      anon_sym_SLASH_GT,
    STATE(60), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [1232] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(201), 1,
      anon_sym_GT,
    ACTIONS(205), 1,
      sym_attribute_name,
    ACTIONS(220), 1,
      anon_sym_SLASH_GT,
    STATE(64), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [1249] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(205), 1,
      sym_attribute_name,
    ACTIONS(211), 1,
      anon_sym_GT,
    ACTIONS(222), 1,
      anon_sym_SLASH_GT,
    STATE(58), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [1266] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(205), 1,
      sym_attribute_name,
    ACTIONS(224), 1,
      anon_sym_GT,
    ACTIONS(226), 1,
      anon_sym_SLASH_GT,
    STATE(60), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [1283] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(205), 1,
      sym_attribute_name,
    ACTIONS(224), 1,
      anon_sym_GT,
    ACTIONS(228), 1,
      anon_sym_SLASH_GT,
    STATE(60), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [1300] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(205), 1,
      sym_attribute_name,
    ACTIONS(207), 1,
      anon_sym_GT,
    ACTIONS(230), 1,
      anon_sym_SLASH_GT,
    STATE(60), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [1317] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(215), 1,
      anon_sym_GT,
    ACTIONS(232), 1,
      sym_attribute_name,
    STATE(66), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [1331] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(235), 1,
      anon_sym_GT,
    ACTIONS(237), 1,
      sym_attribute_name,
    STATE(66), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [1345] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(239), 1,
      sym_attribute_value,
    ACTIONS(241), 1,
      anon_sym_SQUOTE,
    ACTIONS(243), 1,
      anon_sym_DQUOTE,
    STATE(85), 1,
      sym_quoted_attribute_value,
  [1361] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(237), 1,
      sym_attribute_name,
    ACTIONS(245), 1,
      anon_sym_GT,
    STATE(66), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [1375] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(237), 1,
      sym_attribute_name,
    ACTIONS(247), 1,
      anon_sym_GT,
    STATE(69), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [1389] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(237), 1,
      sym_attribute_name,
    ACTIONS(249), 1,
      anon_sym_GT,
    STATE(67), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [1403] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(253), 1,
      anon_sym_EQ,
    ACTIONS(251), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
  [1415] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(255), 1,
      sym_attribute_value,
    ACTIONS(257), 1,
      anon_sym_SQUOTE,
    ACTIONS(259), 1,
      anon_sym_DQUOTE,
    STATE(103), 1,
      sym_quoted_attribute_value,
  [1431] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(261), 1,
      anon_sym_LT_SLASH,
    ACTIONS(263), 1,
      sym_raw_text,
    STATE(14), 1,
      sym_end_tag,
  [1444] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(265), 1,
      anon_sym_LT_SLASH,
    ACTIONS(267), 1,
      sym_raw_text,
    STATE(39), 1,
      sym_end_tag,
  [1457] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(269), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
  [1466] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(271), 1,
      sym__start_tag_name,
    ACTIONS(273), 1,
      sym__script_start_tag_name,
    ACTIONS(275), 1,
      sym__style_start_tag_name,
  [1479] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(273), 1,
      sym__script_start_tag_name,
    ACTIONS(275), 1,
      sym__style_start_tag_name,
    ACTIONS(277), 1,
      sym__start_tag_name,
  [1492] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(279), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
  [1501] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(261), 1,
      anon_sym_LT_SLASH,
    ACTIONS(281), 1,
      sym_raw_text,
    STATE(23), 1,
      sym_end_tag,
  [1514] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(283), 1,
      anon_sym_LT_SLASH_POUND,
    ACTIONS(285), 1,
      sym__implicit_end_tag,
    STATE(25), 1,
      sym_fm_directive_end_tag,
  [1527] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(287), 1,
      anon_sym_LT_SLASH_POUND,
    ACTIONS(289), 1,
      sym__implicit_end_tag,
    STATE(46), 1,
      sym_fm_directive_end_tag,
  [1540] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(265), 1,
      anon_sym_LT_SLASH,
    ACTIONS(291), 1,
      sym_raw_text,
    STATE(37), 1,
      sym_end_tag,
  [1553] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(293), 1,
      anon_sym_EQ,
    ACTIONS(251), 2,
      anon_sym_GT,
      sym_attribute_name,
  [1564] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(295), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
  [1573] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(297), 1,
      sym_identifier,
    STATE(92), 1,
      sym__expression,
  [1583] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(299), 1,
      anon_sym_if,
    STATE(134), 1,
      sym_fm_if_directive_start_tag,
  [1593] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(265), 1,
      anon_sym_LT_SLASH,
    STATE(50), 1,
      sym_end_tag,
  [1603] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(301), 1,
      sym__end_tag_name,
    ACTIONS(303), 1,
      sym_erroneous_end_tag_name,
  [1613] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(305), 1,
      anon_sym_SQUOTE,
    ACTIONS(307), 1,
      aux_sym_quoted_attribute_value_token1,
  [1623] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(303), 1,
      sym_erroneous_end_tag_name,
    ACTIONS(309), 1,
      sym__end_tag_name,
  [1633] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(311), 2,
      sym__implicit_end_tag,
      anon_sym_LT_SLASH_POUND,
  [1641] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(313), 1,
      anon_sym_DQUOTE,
    ACTIONS(315), 1,
      aux_sym_quoted_attribute_value_token2,
  [1651] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(265), 1,
      anon_sym_LT_SLASH,
    STATE(51), 1,
      sym_end_tag,
  [1661] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(313), 1,
      anon_sym_SQUOTE,
    ACTIONS(317), 1,
      aux_sym_quoted_attribute_value_token1,
  [1671] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(319), 2,
      sym_raw_text,
      anon_sym_LT_SLASH,
  [1679] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(321), 2,
      sym_raw_text,
      anon_sym_LT_SLASH,
  [1687] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(323), 2,
      sym_raw_text,
      anon_sym_LT_SLASH,
  [1695] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(325), 2,
      sym_raw_text,
      anon_sym_LT_SLASH,
  [1703] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(261), 1,
      anon_sym_LT_SLASH,
    STATE(15), 1,
      sym_end_tag,
  [1713] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(261), 1,
      anon_sym_LT_SLASH,
    STATE(16), 1,
      sym_end_tag,
  [1723] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(327), 2,
      sym__implicit_end_tag,
      anon_sym_LT_SLASH_POUND,
  [1731] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(295), 2,
      anon_sym_GT,
      sym_attribute_name,
  [1739] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(269), 2,
      anon_sym_GT,
      sym_attribute_name,
  [1747] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(279), 2,
      anon_sym_GT,
      sym_attribute_name,
  [1755] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(329), 1,
      sym_identifier,
    STATE(111), 1,
      sym__expression,
  [1765] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(305), 1,
      anon_sym_DQUOTE,
    ACTIONS(331), 1,
      aux_sym_quoted_attribute_value_token2,
  [1775] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(333), 1,
      anon_sym_GT,
  [1782] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(335), 1,
      anon_sym_GT,
  [1789] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(301), 1,
      sym__end_tag_name,
  [1796] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(311), 1,
      anon_sym_GT,
  [1803] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(337), 1,
      anon_sym_GT,
  [1810] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(339), 1,
      anon_sym_GT,
  [1817] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(341), 1,
      anon_sym_GT,
  [1824] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(343), 1,
      sym__start_tag_name,
  [1831] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(345), 1,
      anon_sym_if,
  [1838] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(347), 1,
      sym_erroneous_end_tag_name,
  [1845] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(349), 1,
      ts_builtin_sym_end,
  [1852] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(351), 1,
      anon_sym_GT,
  [1859] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(353), 1,
      sym__end_tag_name,
  [1866] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(355), 1,
      anon_sym_GT,
  [1873] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(357), 1,
      anon_sym_GT,
  [1880] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(359), 1,
      anon_sym_SQUOTE,
  [1887] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(361), 1,
      anon_sym_GT,
  [1894] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(363), 1,
      anon_sym_GT,
  [1901] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(365), 1,
      aux_sym_doctype_token1,
  [1908] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(367), 1,
      sym__doctype,
  [1915] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(369), 1,
      anon_sym_SQUOTE,
  [1922] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(369), 1,
      anon_sym_DQUOTE,
  [1929] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(359), 1,
      anon_sym_DQUOTE,
  [1936] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(371), 1,
      sym__start_tag_name,
  [1943] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(303), 1,
      sym_erroneous_end_tag_name,
  [1950] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(373), 1,
      aux_sym_doctype_token1,
  [1957] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(375), 1,
      anon_sym_GT,
  [1964] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(377), 1,
      sym__end_tag_name,
  [1971] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(379), 1,
      anon_sym_if,
  [1978] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(309), 1,
      sym__end_tag_name,
  [1985] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(381), 1,
      sym__doctype,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(6)] = 0,
  [SMALL_STATE(7)] = 64,
  [SMALL_STATE(8)] = 128,
  [SMALL_STATE(9)] = 192,
  [SMALL_STATE(10)] = 256,
  [SMALL_STATE(11)] = 318,
  [SMALL_STATE(12)] = 379,
  [SMALL_STATE(13)] = 440,
  [SMALL_STATE(14)] = 457,
  [SMALL_STATE(15)] = 474,
  [SMALL_STATE(16)] = 491,
  [SMALL_STATE(17)] = 508,
  [SMALL_STATE(18)] = 525,
  [SMALL_STATE(19)] = 542,
  [SMALL_STATE(20)] = 559,
  [SMALL_STATE(21)] = 576,
  [SMALL_STATE(22)] = 593,
  [SMALL_STATE(23)] = 610,
  [SMALL_STATE(24)] = 627,
  [SMALL_STATE(25)] = 644,
  [SMALL_STATE(26)] = 661,
  [SMALL_STATE(27)] = 678,
  [SMALL_STATE(28)] = 695,
  [SMALL_STATE(29)] = 712,
  [SMALL_STATE(30)] = 729,
  [SMALL_STATE(31)] = 746,
  [SMALL_STATE(32)] = 763,
  [SMALL_STATE(33)] = 780,
  [SMALL_STATE(34)] = 797,
  [SMALL_STATE(35)] = 814,
  [SMALL_STATE(36)] = 830,
  [SMALL_STATE(37)] = 846,
  [SMALL_STATE(38)] = 862,
  [SMALL_STATE(39)] = 878,
  [SMALL_STATE(40)] = 894,
  [SMALL_STATE(41)] = 910,
  [SMALL_STATE(42)] = 926,
  [SMALL_STATE(43)] = 942,
  [SMALL_STATE(44)] = 958,
  [SMALL_STATE(45)] = 974,
  [SMALL_STATE(46)] = 990,
  [SMALL_STATE(47)] = 1006,
  [SMALL_STATE(48)] = 1022,
  [SMALL_STATE(49)] = 1038,
  [SMALL_STATE(50)] = 1054,
  [SMALL_STATE(51)] = 1070,
  [SMALL_STATE(52)] = 1086,
  [SMALL_STATE(53)] = 1102,
  [SMALL_STATE(54)] = 1118,
  [SMALL_STATE(55)] = 1134,
  [SMALL_STATE(56)] = 1150,
  [SMALL_STATE(57)] = 1166,
  [SMALL_STATE(58)] = 1183,
  [SMALL_STATE(59)] = 1200,
  [SMALL_STATE(60)] = 1217,
  [SMALL_STATE(61)] = 1232,
  [SMALL_STATE(62)] = 1249,
  [SMALL_STATE(63)] = 1266,
  [SMALL_STATE(64)] = 1283,
  [SMALL_STATE(65)] = 1300,
  [SMALL_STATE(66)] = 1317,
  [SMALL_STATE(67)] = 1331,
  [SMALL_STATE(68)] = 1345,
  [SMALL_STATE(69)] = 1361,
  [SMALL_STATE(70)] = 1375,
  [SMALL_STATE(71)] = 1389,
  [SMALL_STATE(72)] = 1403,
  [SMALL_STATE(73)] = 1415,
  [SMALL_STATE(74)] = 1431,
  [SMALL_STATE(75)] = 1444,
  [SMALL_STATE(76)] = 1457,
  [SMALL_STATE(77)] = 1466,
  [SMALL_STATE(78)] = 1479,
  [SMALL_STATE(79)] = 1492,
  [SMALL_STATE(80)] = 1501,
  [SMALL_STATE(81)] = 1514,
  [SMALL_STATE(82)] = 1527,
  [SMALL_STATE(83)] = 1540,
  [SMALL_STATE(84)] = 1553,
  [SMALL_STATE(85)] = 1564,
  [SMALL_STATE(86)] = 1573,
  [SMALL_STATE(87)] = 1583,
  [SMALL_STATE(88)] = 1593,
  [SMALL_STATE(89)] = 1603,
  [SMALL_STATE(90)] = 1613,
  [SMALL_STATE(91)] = 1623,
  [SMALL_STATE(92)] = 1633,
  [SMALL_STATE(93)] = 1641,
  [SMALL_STATE(94)] = 1651,
  [SMALL_STATE(95)] = 1661,
  [SMALL_STATE(96)] = 1671,
  [SMALL_STATE(97)] = 1679,
  [SMALL_STATE(98)] = 1687,
  [SMALL_STATE(99)] = 1695,
  [SMALL_STATE(100)] = 1703,
  [SMALL_STATE(101)] = 1713,
  [SMALL_STATE(102)] = 1723,
  [SMALL_STATE(103)] = 1731,
  [SMALL_STATE(104)] = 1739,
  [SMALL_STATE(105)] = 1747,
  [SMALL_STATE(106)] = 1755,
  [SMALL_STATE(107)] = 1765,
  [SMALL_STATE(108)] = 1775,
  [SMALL_STATE(109)] = 1782,
  [SMALL_STATE(110)] = 1789,
  [SMALL_STATE(111)] = 1796,
  [SMALL_STATE(112)] = 1803,
  [SMALL_STATE(113)] = 1810,
  [SMALL_STATE(114)] = 1817,
  [SMALL_STATE(115)] = 1824,
  [SMALL_STATE(116)] = 1831,
  [SMALL_STATE(117)] = 1838,
  [SMALL_STATE(118)] = 1845,
  [SMALL_STATE(119)] = 1852,
  [SMALL_STATE(120)] = 1859,
  [SMALL_STATE(121)] = 1866,
  [SMALL_STATE(122)] = 1873,
  [SMALL_STATE(123)] = 1880,
  [SMALL_STATE(124)] = 1887,
  [SMALL_STATE(125)] = 1894,
  [SMALL_STATE(126)] = 1901,
  [SMALL_STATE(127)] = 1908,
  [SMALL_STATE(128)] = 1915,
  [SMALL_STATE(129)] = 1922,
  [SMALL_STATE(130)] = 1929,
  [SMALL_STATE(131)] = 1936,
  [SMALL_STATE(132)] = 1943,
  [SMALL_STATE(133)] = 1950,
  [SMALL_STATE(134)] = 1957,
  [SMALL_STATE(135)] = 1964,
  [SMALL_STATE(136)] = 1971,
  [SMALL_STATE(137)] = 1978,
  [SMALL_STATE(138)] = 1985,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fragment, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(127),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(78),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(115),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(86),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(117),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(138),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(77),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(131),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(132),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(135),
  [31] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [35] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(120),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [43] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [51] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [57] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [63] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(138),
  [66] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(77),
  [69] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(131),
  [72] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(87),
  [75] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(86),
  [78] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(132),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_fragment_repeat1, 2),
  [83] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(10),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fragment, 1),
  [88] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [90] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(127),
  [93] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(78),
  [96] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(115),
  [99] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(117),
  [102] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(12),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_end_tag, 3),
  [107] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_end_tag, 3),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_script_element, 2),
  [111] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_script_element, 2),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_style_element, 3),
  [115] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_style_element, 3),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_script_element, 3),
  [119] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_script_element, 3),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fm_macro, 3),
  [123] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_fm_macro, 3),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element, 3),
  [127] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_element, 3),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_erroneous_end_tag, 3),
  [131] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_erroneous_end_tag, 3),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fm_macro_self_closing_tag, 3),
  [135] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_fm_macro_self_closing_tag, 3),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_self_closing_tag, 3),
  [139] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_self_closing_tag, 3),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fm_directive_end_tag, 3),
  [143] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_fm_directive_end_tag, 3),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_style_element, 2),
  [147] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_style_element, 2),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_doctype, 4),
  [151] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_doctype, 4),
  [153] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fm_directive, 2),
  [155] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_fm_directive, 2),
  [157] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fm_macro, 2),
  [159] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_fm_macro, 2),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_self_closing_tag, 4),
  [163] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_self_closing_tag, 4),
  [165] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element, 2),
  [167] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_element, 2),
  [169] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fm_macro, 1),
  [171] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_fm_macro, 1),
  [173] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fm_macro_self_closing_tag, 4),
  [175] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_fm_macro_self_closing_tag, 4),
  [177] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element, 1),
  [179] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_element, 1),
  [181] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fm_macro_start_tag, 3),
  [183] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_fm_macro_start_tag, 3),
  [185] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fm_macro_start_tag, 4),
  [187] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_fm_macro_start_tag, 4),
  [189] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fm_macro_end_tag, 3),
  [191] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_fm_macro_end_tag, 3),
  [193] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_start_tag, 3),
  [195] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_start_tag, 3),
  [197] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_start_tag, 4),
  [199] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_start_tag, 4),
  [201] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [203] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [205] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [207] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [209] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [211] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [213] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [215] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_start_tag_repeat1, 2),
  [217] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_start_tag_repeat1, 2), SHIFT_REPEAT(72),
  [220] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [222] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [224] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [226] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [228] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [230] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [232] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_start_tag_repeat1, 2), SHIFT_REPEAT(84),
  [235] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [237] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [239] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [241] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [243] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [245] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [247] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [249] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [251] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 1),
  [253] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [255] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [257] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [259] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [261] = {.entry = {.count = 1, .reusable = true}}, SHIFT(137),
  [263] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [265] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [267] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [269] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_attribute_value, 2),
  [271] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [273] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [275] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [277] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [279] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_attribute_value, 3),
  [281] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [283] = {.entry = {.count = 1, .reusable = true}}, SHIFT(136),
  [285] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [287] = {.entry = {.count = 1, .reusable = true}}, SHIFT(116),
  [289] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [291] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [293] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [295] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 3),
  [297] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [299] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [301] = {.entry = {.count = 1, .reusable = true}}, SHIFT(112),
  [303] = {.entry = {.count = 1, .reusable = true}}, SHIFT(114),
  [305] = {.entry = {.count = 1, .reusable = false}}, SHIFT(76),
  [307] = {.entry = {.count = 1, .reusable = true}}, SHIFT(123),
  [309] = {.entry = {.count = 1, .reusable = true}}, SHIFT(122),
  [311] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fm_if_directive_start_tag, 2),
  [313] = {.entry = {.count = 1, .reusable = false}}, SHIFT(104),
  [315] = {.entry = {.count = 1, .reusable = true}}, SHIFT(129),
  [317] = {.entry = {.count = 1, .reusable = true}}, SHIFT(128),
  [319] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_style_start_tag, 4),
  [321] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_script_start_tag, 3),
  [323] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_script_start_tag, 4),
  [325] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_style_start_tag, 3),
  [327] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fm_directive_start_tag, 3),
  [329] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [331] = {.entry = {.count = 1, .reusable = true}}, SHIFT(130),
  [333] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [335] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [337] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [339] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [341] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [343] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [345] = {.entry = {.count = 1, .reusable = true}}, SHIFT(121),
  [347] = {.entry = {.count = 1, .reusable = true}}, SHIFT(113),
  [349] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [351] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [353] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [355] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [357] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [359] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [361] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [363] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [365] = {.entry = {.count = 1, .reusable = true}}, SHIFT(125),
  [367] = {.entry = {.count = 1, .reusable = true}}, SHIFT(126),
  [369] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [371] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [373] = {.entry = {.count = 1, .reusable = true}}, SHIFT(119),
  [375] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [377] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [379] = {.entry = {.count = 1, .reusable = true}}, SHIFT(124),
  [381] = {.entry = {.count = 1, .reusable = true}}, SHIFT(133),
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_freemarker_external_scanner_create(void);
void tree_sitter_freemarker_external_scanner_destroy(void *);
bool tree_sitter_freemarker_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_freemarker_external_scanner_serialize(void *, char *);
void tree_sitter_freemarker_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_freemarker(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_freemarker_external_scanner_create,
      tree_sitter_freemarker_external_scanner_destroy,
      tree_sitter_freemarker_external_scanner_scan,
      tree_sitter_freemarker_external_scanner_serialize,
      tree_sitter_freemarker_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
